version: "3"
services:
  consumer-app:
    build:
      context: .
      dockerfile: ./src/consumer-app/Dockerfile
    container_name: rabbit-consumer
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: consumer-app
      SERVICE_TAGS: dev
    volumes:
      - ./src/consumer-app/:/var/www/

  publisher-app:
    build:
      context: .
      dockerfile: ./src/publisher-app/Dockerfile
    container_name: rabbit-publisher
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: publisher-app
      SERVICE_TAGS: dev
    volumes:
      - ./src/publisher-app/:/var/www/

  ampq:
    image: library/rabbitmq:3.8-alpine
    container_name: rabbit
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:1.18-alpine
    container_name: rabbit-nginx
    depends_on:
      - consumer-app
      - publisher-app
    restart: unless-stopped
    ports:
      - 7001:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx