version: "3"
services:
  consumer-app:
    build:
      args:
        user: www
        uid: 1000
        port: 9000
      context: ./src/consumer-app/
      dockerfile: Dockerfile
    container_name: rabbit-consumer
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      SERVICE_NAME: consumer-app
      SERVICE_TAGS: dev
    ports:
      - 9000:9000
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./src/consumer-app/:/var/www/

  publisher-app:
    build:
      args:
        user: www
        uid: 1000
        port: 9001
      context: ./src/publisher-app/
      dockerfile: Dockerfile
    container_name: rabbit-publisher
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      SERVICE_NAME: publisher-app
      SERVICE_TAGS: dev
    ports:
      - 9001:9001
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./src/publisher-app/:/var/www/

  ampq:
    image: library/rabbitmq:3.8-alpine
    container_name: rabbit
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:1.18-alpine
    container_name: rabbit-nginx
    depends_on:
      - consumer-app
      - publisher-app
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/logs/nginx/:/var/log/nginx/